jaguarete/jaguarete/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete/shop/urls.py
from django.urls import path
 
from . import views
 
app_name = 'shop'

urlpatterns = [
     path ('', views.index, name='base'),
     path ('login', views.login_page, name='login'),
     path ('logout', views.logout_page, name='logout'),
     path('register', views.register_page, name='register'),
     path ('contacto', views.contacto, name='contacto'), 
     path ('acerca', views.acerca, name='acerca'), 
     
     path ('product_list', views.product_list, name='product_list'),
     path ('<slug:category_id>', views.product_list, name='product_list_by_category'),
     path ('<int:id>/<slug:sku>/', views.product_detail, name='product_detail'),
     
]

jaguarete/shop/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.urls import reverse


 
 
# Create your models here.
 
class Categorias(models.Model):
    descripcion = models.CharField(max_length=200, db_index=True)
    id_cat = models.SlugField(max_length=200, db_index=True, unique=True)
 
    class Meta:
        ordering = ('descripcion',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
 
    def __str__(self):
        return self.descripcion
    
    def save(self, *args, **kwargs):
        if not self.id_cat:
            self.id_cat = slugify(self.descripcion)
        super(Categorias, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.id_cat])
 
 
class Productos(models.Model):
    categoria = models.ForeignKey(Categorias, related_name='productos', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200, db_index=True)
    sku = models.SlugField(max_length=200, db_index=True)
    imagen = models.ImageField(upload_to='productos', blank=True)
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.PositiveIntegerField(default=0)
 
    class Meta:
        ordering = ('titulo',)
        index_together = (('id', 'sku'),)
 
    def __str__(self):
        return self.titulo
    
    def save(self, *args, **kwargs):
        if not self.sku:
            self.sku = slugify(self.titulo)
        super(Productos, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.sku])

class Carrito(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Productos)
    start_date = models.DateField(auto_now_add=True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


  
  

jaguarete/shop/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CustomUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

jaguarete/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CustomUserForm
from .models import Categorias, Productos
 
 
# Create your views here.
def index(request):
    return render(request, 'base.html')
 
def product_list(request, category_id=None):
    category = None
    categories = Categorias.objects.all()
    products = Productos.objects.all()


    if category_id:
        category = get_object_or_404(Categorias, id_cat=category_id)
        products = products.filter(categoria=category)
    return render(request, 'list.html', {
            'category': category, 
            'categories': categories, 
            'productos': products
            })
 
def product_detail(request, id, sku):
    product = get_object_or_404(Productos, id=id, sku=sku)
    return render(request, 'detail.html', {'product': product})

def acerca(request):
   return render(request, 'acerca.html')

def contacto(request):
   return render(request, 'contacto.html')

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('shop:base')
        else:
            messages.info(request, 'Try again! username or password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def logout_page(request):
    logout(request)
    return redirect('shop:base')

@login_required(login_url='shop:login')

def register_page(request):
    if request.method != 'POST':
        form = CustomUserForm()
    else:
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('shop:login')
            
    context = {'form': form}
    return render(request, 'register.html', context)

jaguarete/shop/templates/acerca.html
<!-- acerca.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container m-auto">
    <div class="tarjeta">
        <h1>Sobre Nosotros</h1>
        <p>
           Mi nombre Jos&eacute; Navarrete, agradecido con el profesor por la paciencia durante el curso.
        </p>
        <p>
            Agradecido con Polotic Misiones, por la oportunidad de tomar un curso como el DESARROLLO WEB FULLSTACK CON PYTHON Y JAVASCRIPT 
        </p>
        <p>
            La aplicaci&oacute;n Jaguarete Shop forma parte del proyecto final el cual consist&iacute;a en la implementaci&oacute;n
            de una tienda Virtual, en su representaci&oacute;n b&aacute;sica o el producto m&iacute;nimo viable para obtener la cantidad
            m&aacute;xima de conocimiento validando lo aprendido durante el curso.
        </p>
    </div>
</div>

{% endblock %}

jaguarete/shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static '/css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

        <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Jaguarete Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
         
                <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="product_list">Productos</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="admin/shop/productos/">Admin Productos</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="logout">Salir</a>
                </li>
                </ul>
                <div class="my-personal-info my-auto mr-sm-2">
                    <div class="d-flex flex-column">
                        <div>
                            <p>
                                Bienvenido, 
                                <span class="bold"> {{ user.first_name }}</span>
                            </p>
                        </div>
                        <div>
                            <Nav.Link class="menuLinks mr-3" href="micarrito">
                                Mi Carrito
                            </Nav.Link>
                        </div>
                    </div>
                </div>
            {% else %}
                <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="acerca">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contacto">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="login">Ingresar</a>
                </li>
                </ul>
                <div class="my-auto p-md-2">
                    <div class="d-flex flex-column">
                        <div class="p-0">                           
                            <a href="login" class="btn boton-uva text-uppercase">Ingresar</a>
                        </div>
                        <div class="pt-1 text-center">                          
                            <a href="register" class="ahrefRegistrar">o Registrarse</a>                          
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
      </nav>
<div id="content">
    {% block content %}
    <div class="m-auto container">
        <div class="row crema-f-bg my-2">
            <div class="col-sm text-center">
                <div class="d-flex flex-column align-items-center h-100">
                    <div class="m-auto">
                        <p class="bienvenida">Bienvenido a su Tienda</p>
                        <p class="bienvenida_titulo">
                            <span >Jaguarete</span> <span style="color:rgb(187, 222, 106)">Shop</span> 
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm p-0">
                <img src="{% static '/media/myshop_logo.png' %}" class="img-fluid" />
            </div>
        </div>
    </div>
    {% endblock %}
</div>
<div>
    <footer class="footer mt-auto py-3">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-9 d-flex align-items-center">
                    <div>Jaguarete Shop &copy; Todos los Derechos Reservados 2021</div>
                </div>
                <div class="col-md-3 mt-2 mt-md-0">
                    <div class="float-md-right">
                        <i class="fab fa-facebook"></i>
                        <i class="fab fa-instagram"></i>
                        <i class="fab fa-twitter"></i>
                        <i class="fab fa-youtube"></i>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

jaguarete/shop/templates/contacto.html
<!-- contacto.html -->
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="m-auto container">
    <div class="row justify-content-center contacto">
        <br> Contactenos, estamos para servirle <br><br>
       <ul style="list-style: none;">
        <li><i class="fab fa-instagram"> Correo: josnavch@gmail.com</i> </li>
        <li><i class="fas fa-phone-square"> Teléfono: +506 88895222</i> </li>
        <li> <i class="fas fa-map-marker">Dirección: San José, Costa Rica</i> </li>
        </ul>
    </div>
</div>

{% endblock %}

jaguarete/shop/templates/detail.html
{% extends "base.html" %}
{% load static %}
 
{% block title %}
  {% if categoria %}{{ categoria.descripcion }}{% else %}Productos{% endif %}
{% endblock %}
 
{% block content %}
    <div class="product-detail">
    <img src="{% if product.imagen %}{{ product.imagen.url }}{% else %}{% static 'media/No_image_available.png' %}{% endif %}">
    <h1>{{ product.titulo }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.categoria }}</a></h2>
    <p class="price">${{ product.precio }}</p>
      {{ product.descripcion|linebreaks }}
  </div>
{% endblock %}

jaguarete/shop/templates/list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
{% if category %}{{ category.descripcion }}{% else %}Productos{% endif %}
{% endblock %}
 
{% block content %}

<div class="sidebar">
            <h3 class="sidebar_tittle">Categorias</h3>
            <ul class="active">
                {% if not category %}{% endif %}
                    <a href="{% url "shop:product_list" %}">All</a>
                
                {% for c in categories %}
                    {% if category.id_cat == c.id_cat %}{% endif %}
                        <a href="{{ c.get_absolute_url }}">{{ c.descripcion }}</a>
                    
                {% endfor %}
            </ul>
        </div>
        <div id="main" class="content">
            <h1>{% if category %}{{ category.descripcion }}{% else %}
            Productos{% endif %}</h1>
            <div class="carousel">
                <div class="horizontal-scroll-wrapper">
                    {% for product in productos %}
                        <div class="card-deck">
                            <div class="card">
                                <div class="card-img-top text-center">
                                    <a href="{{ product.get_absolute_url }}">
                                        {% load thumbnail %}
                                        {% if product.imagen  %}
                                            {% thumbnail product.imagen '300x200' as im %}
                                                <img src="{{ im.url }}">
                                            {% endthumbnail %}
                                        {% else %}
                                            <img src="{% static 'media/No_image_available.png' %}" style="height: 200px; width: 200px;">
                                        {% endif %} 
                                    </a>

                                </div>
                                <div class="card-body text-center">
                                    <p class="card-title" href="{{ product.get_absolute_url }}">{{ product.titulo }}</p>
                                    
                                </div>
                                <div class="card-footer d-flex">
                                    <div> <p class="card-text pricing-card-title">${{ product.precio }} </p> </div>
                                    <div class="ml-auto">
                                        <i class="fas fa-cart-plus btn"></i>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    {% endfor %}   
                </div>    
            </div>
        </div>
{% endblock %}

jaguarete/shop/templates/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>




<div class="login-page">
  <div class="form">
    <form method="POST" action="">
      {% csrf_token %}
      <h3 class="login-title">LOGIN</h3>
      <div class="input-group mb-3">
        <input type="text" name="username" placeholder="Username..." class="form-control">
      </div>
      <div class="input-group mb-2">
          <input type="password" name="password" placeholder="Password..." class="form-control" >
      </div>
      <button type="submit"> Submit </button>
      <p class="message">Don't have an account? <a href="{% url 'shop:register' %}">Registrarse</a></p>
    </form>
{% for message in messages %}
   <p class= "text-center">{{message}}</p>
{% endfor %}
  </div>
</div>




<script>
    $('.alternate').click(function () {
        $('form').animate({ height: "toggle", opacity: "toggle" }, "slow");
    });
</script>

jaguarete/shop/templates/logout.html
<h1>Logged out</h1>
<h2>Gracias por su visita, a nuestra tienda Jaguarete Shop</h2>
<h3>Tenga un buen dia!</h3>
<a href="{% url 'shop:home' %}"> Ingresar nuevamente</a>

jaguarete/shop/templates/register.html
{% load static %}

<link rel="stylesheet"  href="{% static 'css/register.css' %}">

<div class="register-page">

    <div class="form">
      <form class="register-form" method="POST" action="">
        {% csrf_token %}
        <h2 class="register-title">Registrarse</h3>
        <h4>{{form.username.label}}</h4>
        {{form.username}}
        <h4>{{form.email.label}}</h4>
        {{form.email}}
        <h4>{{form.password1.label}}</h4>
        {{form.password1}}
        <h4>{{form.password2.label}}</h4>
        {{form.password2}}
        <button type="submit"> Create </button>
        <p class="message">Already registered? <a href="{% url 'login' %}">Log In</a></p>
        </form>
        {{ form.errors }}
    </div>
  
  </div>